version: '3.9'
services:
  mongodb:
    image: mongo:4.4
    volumes:
    - ${PWD}/data/mongodb_data:/data/db
    ports:
    - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 10
  redis:
    image: redis
    volumes:
    - ${PWD}/data/redis_data:/data
    ports:
    - 6379:6379
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 1s
      timeout: 3s
      retries: 30
  localstack-pro:
    image: localstack/localstack-pro
    ports:
    - 4566:4566
    - 4510-4559:4510-4559
    environment:
      PERSISTENCE: '1'
      DOCKER_HOST: unix:///var/run/docker.sock
      LOCALSTACK_API_KEY: ${LOCALSTACK_API_KEY}
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${PWD}/data/localstack_pro_data:/var/lib/localstack
