version: "3.9"

services:
  mongodb:
    image: mongo:4.4
    volumes:
      - ${PWD}/data/mongodb_data:/data/db
    ports:
      - "19023:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 10
  minio:
    image: minio/minio:RELEASE.2021-06-09T18-51-39Z
    command: [ "server", "/data" ]
    volumes:
      - ${PWD}/data/minio_data:/data
    ports:
      - "19025:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
  minio-bootstrap:
    image: minio/mc:RELEASE.2021-06-13T17-48-22Z
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set local http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb --ignore-existing local/minigplus;
      /usr/bin/mc admin user add local stsadmin stsadmin-secret;
      /usr/bin/mc admin policy add local rwall /root/dev-rwall-role-policy.json;
      /usr/bin/mc admin policy set local rwall user=stsadmin;
      /usr/bin/mc policy set-json /root/dev-public-read-bucket-policy.json local/minigplus;
      "
    volumes:
      - ${PWD}/scripts/dev-rwall-role-policy.json:/root/dev-rwall-role-policy.json
      - ${PWD}/scripts/dev-public-read-bucket-policy.json:/root/dev-public-read-bucket-policy.json
    depends_on:
      - minio
