version: "3.9"

services:
  mongodb:
    image: mongo:4.4
    volumes:
      - ${PWD}/data/mongodb_data:/data/db
    ports:
      - "19023:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 10
  minio:
    image: minio/minio:RELEASE.2021-06-09T18-51-39Z
    command: [ "server", "/data" ]
    volumes:
      - ${PWD}/data/minio_data:/data
    ports:
      - "19025:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
  minio-bootstrap:
    image: minio/mc:RELEASE.2021-06-13T17-48-22Z
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set local http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb --ignore-existing local/minigplus;
      "
    depends_on:
      - minio
  nginx:
    image: nginx:1.21.1
    command: |
      bash -c 'bash -s <<EOF
        cat > /etc/nginx/nginx.conf <<EON
          daemon off;
          events {
            worker_connections 768;
          }
          http {
            gzip on;
            gzip_disable "msie6";
            include /etc/nginx/mime.types;
            server {
              listen 80;
              server_name localhost:19026;

              return 301 http://localhost:19025/minigplus$$request_uri;
            }
          }
      EON
      nginx
      EOF'
    ports:
      - "19026:80"
    healthcheck:
      test: [ "CMD-SHELL", "wget -O /dev/null http://localhost || exit 1" ]
      timeout: 10s
    depends_on:
      - minio
