version: "3.9"

services:
  minio-bootstrap:
    image: minio/mc:RELEASE.2021-06-13T17-48-22Z
    entrypoint: /root/minio-bootstrap.sh
    volumes:
      - ${PWD}/scripts/minio-bootstrap.sh:/root/minio-bootstrap.sh
      - ${PWD}/scripts/dev-rwall-role-policy.json:/root/dev-rwall-role-policy.json
      - ${PWD}/scripts/dev-public-read-bucket-policy.json:/root/dev-public-read-bucket-policy.json
