name: OpenAPI Codegen

on:
 push:
   branches: ['master']
   paths:
     - 'swagger.yaml'
     - '.github/workflows/openapi-codegen.yaml'

jobs:
  generate-dart-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Dart SDK
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: dart
          openapi-file: swagger.yaml
          template-dir: generated-dart-sdk

      - name: Checkout Dart SDK repository
        uses: actions/checkout@v3
        with:
          repository: pill-city/dart-sdk
          path: dart-sdk
          token: ${{ secrets.GH_TOKEN }}

      - name: Copy all contents into Dart SDK repository
        run: rsync -av ./generated-dart-sdk/ ./dart-sdk

      - name: Push Dart SDK repository
        working-directory: dart-sdk
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "Update SDK"
          git push
