name: Swagger codegen

on:
  push:
    branches: ['master']

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate typescript-fetch client SDK
        uses: ducksify/swagger-codegen-action@v3.0
        with:
          args: generate -i swagger.yaml -o sdk-typescript-fetch -l typescript-fetch

      - name: ls
        run: ls sdk-typescript-fetch
