name: Swagger codegen

on:
  push:
    branches: ['master']
    paths:
      - 'swagger.yaml'
      - '.github/workflows/swagger-codegen.yaml'

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate TypeScript client SDK
        uses: ducksify/swagger-codegen-action@v3.0
        with:
          args: generate -i swagger.yaml -o gen-typescript-sdk -l typescript-axios --additional-properties npmName=@pill-city/typescript-sdk,npmVersion=0.0.1

      - name: Checkout typescript-sdk
        uses: actions/checkout@v3
        with:
          repository: pill-city/typescript-sdk
          path: typescript-sdk
          token: ${{ secrets.GH_TOKEN }}

      - name: Copy all contents from gen-typescript-sdk into typescript-sdk
        run: rsync -av ./gen-typescript-sdk/ ./typescript-sdk

      - name: Push typescript-sdk
        working-directory: typescript-sdk
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "Update SDK"
          git push
