name: Swagger codegen

on:
  push:
    branches: ['master']

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate typescript-fetch client SDK
        uses: ducksify/swagger-codegen-action@v3.0

      - name: ls
        run: ls
