name: Swagger codegen

on:
  push:
    branches: ['master']

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create folder for typescript-fetch client SDK
        run: mkdir -p typescript-fetch-sdk

      - name: Generate typescript-fetch client SDK
        uses: ducksify/swagger-codegen-action@v3.0
        args:
          - generate
          - -i
          - ../swagger.yaml
          - -l
          - typescript-fetch
        working-directory: typescript-fetch-sdk

      - name: ls
        working-directory: typescript-fetch-sdk
        run: ls
