name: Web build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        working-directory: ./web
        run: yarn install
      - uses: borales/actions-yarn@v2.3.0
        working-directory: ./web
        run: yarn build
      - uses: borales/actions-yarn@v2.3.0
        working-directory: ./web
        run: yarn test
